<?php

use App\Services\SecurityRosterService;
use App\Models\Company;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('security:generate-roster {--company_id=} {--month=} {--year=} {--anchor=2026-04-28} {--cycle=PPSSMMOO} {--force=0} {--reason=} {--instruction_ref=} {--actor_user_id=}', function () {
    if (!Schema::hasTable('security_shift_definitions') || !Schema::hasTable('security_rosters')) {
        $this->error('Tabel roster security belum tersedia. Jalankan migration dulu.');
        return 1;
    }
    $hasRosterChangeLogs = Schema::hasTable('security_roster_change_logs');

    $month = (int) ($this->option('month') ?: date('n'));
    $year = (int) ($this->option('year') ?: date('Y'));
    if ($month < 1 || $month > 12 || $year < 2020 || $year > 2100) {
        $this->error('Parameter month/year tidak valid.');
        return 1;
    }

    $anchor = trim((string) $this->option('anchor'));
    if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $anchor)) {
        $this->error('Format anchor harus YYYY-MM-DD.');
        return 1;
    }

    $rawCycle = strtoupper(trim((string) $this->option('cycle')));
    $rawCycle = str_replace([' ', ',', '-', '_'], '', $rawCycle);
    if ($rawCycle === '' || strlen($rawCycle) < 2) {
        $this->error('Cycle tidak valid. Contoh: PPSSMMOO');
        return 1;
    }

    $cycle = [];
    for ($i = 0; $i < strlen($rawCycle); $i++) {
        $ch = $rawCycle[$i];
        if ($ch === 'O') {
            $cycle[] = 'OFF';
        } elseif (in_array($ch, ['P', 'S', 'M'], true)) {
            $cycle[] = $ch;
        } else {
            $this->error('Cycle hanya boleh berisi P/S/M/O.');
            return 1;
        }
    }

    $companyIdOpt = (int) ($this->option('company_id') ?: 0);
    $companyQuery = Company::query();
    if (Schema::hasColumn('companies', 'is_active')) {
        $companyQuery->where('is_active', 1);
    }
    if ($companyIdOpt > 0) {
        $companyQuery->where('id', $companyIdOpt);
    }
    $companies = $companyQuery->get(['id', 'company_name']);
    if ($companies->isEmpty()) {
        $this->warn('Tidak ada company aktif untuk diproses.');
        return 0;
    }

    $periodStart = DateTimeImmutable::createFromFormat('Y-m-d', sprintf('%04d-%02d-01', $year, $month));
    if (!$periodStart) {
        $this->error('Tidak bisa membentuk tanggal awal periode.');
        return 1;
    }
    $periodEnd = $periodStart->modify('last day of this month');

    $anchorDate = DateTimeImmutable::createFromFormat('Y-m-d', $anchor);
    if (!$anchorDate) {
        $this->error('Anchor date tidak valid.');
        return 1;
    }

    $force = (int) ($this->option('force') ?: 0) === 1;
    $reason = trim((string) ($this->option('reason') ?: 'Generated by security:generate-roster'));
    $instructionRef = trim((string) ($this->option('instruction_ref') ?: ''));
    $actorUserId = (int) ($this->option('actor_user_id') ?: 0);
    $written = 0;
    $skipped = 0;
    $logged = 0;

    foreach ($companies as $company) {
        $companyId = (int) ($company->id ?? 0);
        if ($companyId <= 0) {
            continue;
        }
        SecurityRosterService::ensureDefaultShiftDefinitionsForCompany($companyId);

        $shiftDefs = DB::table('security_shift_definitions')
            ->where('company_id', $companyId)
            ->where('is_active', 1)
            ->get(['code', 'start_time', 'end_time', 'cross_day'])
            ->keyBy('code');

        foreach (['P', 'S', 'M', 'OFF'] as $requiredCode) {
            if (!isset($shiftDefs[$requiredCode])) {
                $this->error('Company ID ' . $companyId . ' belum punya shift definition lengkap. Jalankan seeder.');
                return 1;
            }
        }

        $employees = DB::table('employees')
            ->where('company_id', $companyId)
            ->where(function ($q) {
                $q->whereRaw("UPPER(COALESCE(position, '')) LIKE '%SECURITY%'")
                  ->orWhereRaw("UPPER(COALESCE(position, '')) LIKE '%SCURITY%'")
                  ->orWhereRaw("UPPER(COALESCE(position, '')) LIKE '%SATPAM%'");
            })
            ->whereRaw("UPPER(COALESCE(position, '')) NOT LIKE '%KEPALA SECURITY%'")
            ->whereRaw("UPPER(COALESCE(position, '')) NOT LIKE '%KEPALA SCURITY%'")
            ->get(['id', 'name', 'position']);

        foreach ($employees as $employee) {
            $employeeId = (int) ($employee->id ?? 0);
            if ($employeeId <= 0) {
                continue;
            }

            $cursor = $periodStart;
            while ($cursor <= $periodEnd) {
                $daysDelta = (int) floor(($cursor->getTimestamp() - $anchorDate->getTimestamp()) / 86400);
                $idx = (($daysDelta % count($cycle)) + count($cycle)) % count($cycle);
                $shiftCode = $cycle[$idx];

                $workDate = $cursor->format('Y-m-d');
                $def = $shiftDefs[$shiftCode] ?? null;

                $startAt = null;
                $endAt = null;
                if ($def && $shiftCode !== 'OFF' && !empty($def->start_time) && !empty($def->end_time)) {
                    $startAt = $workDate . ' ' . substr((string) $def->start_time, 0, 8);
                    $endDate = $workDate;
                    if ((int) ($def->cross_day ?? 0) === 1) {
                        $endDate = $cursor->modify('+1 day')->format('Y-m-d');
                    }
                    $endAt = $endDate . ' ' . substr((string) $def->end_time, 0, 8);
                }

                $existing = DB::table('security_rosters')
                    ->where('company_id', $companyId)
                    ->where('employee_id', $employeeId)
                    ->where('work_date', $workDate)
                    ->first([
                        'id',
                        'company_id',
                        'employee_id',
                        'work_date',
                        'shift_code',
                        'shift_start_at',
                        'shift_end_at',
                        'source',
                        'note',
                        'version_no',
                    ]);

                if ($existing && !$force) {
                    $source = strtoupper(trim((string) ($existing->source ?? '')));
                    if (in_array($source, ['MANUAL', 'SWAP', 'REPLACE'], true)) {
                        $skipped++;
                        $cursor = $cursor->modify('+1 day');
                        continue;
                    }
                }

                $versionNo = (int) (($existing->version_no ?? 0) ?: 0);
                DB::table('security_rosters')->updateOrInsert(
                    [
                        'company_id' => $companyId,
                        'employee_id' => $employeeId,
                        'work_date' => $workDate,
                    ],
                    [
                        'shift_code' => $shiftCode,
                        'shift_start_at' => $startAt,
                        'shift_end_at' => $endAt,
                        'source' => 'GENERATED',
                        'note' => 'Generated by security:generate-roster',
                        'version_no' => max(1, $versionNo + 1),
                        'updated_at' => now(),
                        'created_at' => now(),
                    ]
                );
                $written++;

                $after = DB::table('security_rosters')
                    ->where('company_id', $companyId)
                    ->where('employee_id', $employeeId)
                    ->where('work_date', $workDate)
                    ->first([
                        'id',
                        'company_id',
                        'employee_id',
                        'work_date',
                        'shift_code',
                        'shift_start_at',
                        'shift_end_at',
                        'source',
                        'note',
                        'version_no',
                    ]);

                if ($hasRosterChangeLogs && $after) {
                    $action = $existing ? 'UPDATE' : 'CREATE';
                    DB::table('security_roster_change_logs')->insert([
                        'company_id' => $companyId,
                        'roster_id' => (int) ($after->id ?? 0) ?: null,
                        'employee_id' => $employeeId,
                        'work_date' => $workDate,
                        'action' => $action,
                        'before_json' => $existing ? json_encode($existing, JSON_UNESCAPED_UNICODE) : null,
                        'after_json' => json_encode($after, JSON_UNESCAPED_UNICODE),
                        'reason' => $reason !== '' ? $reason : null,
                        'instruction_ref' => $instructionRef !== '' ? $instructionRef : null,
                        'actor_user_id' => $actorUserId > 0 ? $actorUserId : null,
                        'created_at' => now(),
                    ]);
                    $logged++;
                }

                $cursor = $cursor->modify('+1 day');
            }
        }
    }

    $this->info('Roster generation selesai.');
    $this->line('Written: ' . $written);
    $this->line('Skipped (manual/swap/replace): ' . $skipped);
    if ($hasRosterChangeLogs) {
        $this->line('Change logs written: ' . $logged);
    }

    return 0;
})->purpose('Generate security roster by monthly pattern (default PPSSMMOO)');

Artisan::command('security:swap-roster
    {--company_id=}
    {--date=}
    {--employee_a=}
    {--employee_b=}
    {--reason=}
    {--instruction_ref=}
    {--actor_user_id=}', function () {
    if (!Schema::hasTable('security_rosters')) {
        $this->error('Tabel security_rosters belum ada. Jalankan migration dulu.');
        return 1;
    }

    $companyId = (int) ($this->option('company_id') ?: 0);
    $workDate = trim((string) ($this->option('date') ?: ''));
    $employeeA = (int) ($this->option('employee_a') ?: 0);
    $employeeB = (int) ($this->option('employee_b') ?: 0);
    $reason = trim((string) ($this->option('reason') ?: 'Swap by admin aplikasi'));
    $instructionRef = trim((string) ($this->option('instruction_ref') ?: ''));
    $actorUserId = (int) ($this->option('actor_user_id') ?: 0);

    if ($companyId <= 0 || $employeeA <= 0 || $employeeB <= 0 || $employeeA === $employeeB) {
        $this->error('company_id, employee_a, employee_b wajib valid dan berbeda.');
        return 1;
    }
    if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $workDate)) {
        $this->error('Format --date harus YYYY-MM-DD.');
        return 1;
    }

    try {
        $result = SecurityRosterService::applySwap(
            $companyId,
            $employeeA,
            $employeeB,
            $workDate,
            $reason !== '' ? $reason : null,
            $instructionRef !== '' ? $instructionRef : null,
            $actorUserId > 0 ? $actorUserId : null
        );
    } catch (\Throwable $e) {
        $this->error('Gagal swap roster: ' . $e->getMessage());
        return 1;
    }

    $this->info('Swap roster berhasil.');
    $this->line('Employee A shift baru: ' . (string) ($result['employee_a_shift'] ?? '-'));
    $this->line('Employee B shift baru: ' . (string) ($result['employee_b_shift'] ?? '-'));
    return 0;
})->purpose('Swap roster dua personel security pada tanggal tertentu');

Artisan::command('security:replace-roster
    {--company_id=}
    {--date=}
    {--from_employee=}
    {--to_employee=}
    {--reason=}
    {--instruction_ref=}
    {--actor_user_id=}', function () {
    if (!Schema::hasTable('security_rosters')) {
        $this->error('Tabel security_rosters belum ada. Jalankan migration dulu.');
        return 1;
    }

    $companyId = (int) ($this->option('company_id') ?: 0);
    $workDate = trim((string) ($this->option('date') ?: ''));
    $fromEmployee = (int) ($this->option('from_employee') ?: 0);
    $toEmployee = (int) ($this->option('to_employee') ?: 0);
    $reason = trim((string) ($this->option('reason') ?: 'Replace by admin aplikasi'));
    $instructionRef = trim((string) ($this->option('instruction_ref') ?: ''));
    $actorUserId = (int) ($this->option('actor_user_id') ?: 0);

    if ($companyId <= 0 || $fromEmployee <= 0 || $toEmployee <= 0 || $fromEmployee === $toEmployee) {
        $this->error('company_id, from_employee, to_employee wajib valid dan berbeda.');
        return 1;
    }
    if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $workDate)) {
        $this->error('Format --date harus YYYY-MM-DD.');
        return 1;
    }

    try {
        $result = SecurityRosterService::applyReplace(
            $companyId,
            $fromEmployee,
            $toEmployee,
            $workDate,
            $reason !== '' ? $reason : null,
            $instructionRef !== '' ? $instructionRef : null,
            $actorUserId > 0 ? $actorUserId : null
        );
    } catch (\Throwable $e) {
        $this->error('Gagal replace roster: ' . $e->getMessage());
        return 1;
    }

    $this->info('Replace roster berhasil.');
    $this->line('From employee shift baru: ' . (string) ($result['from_employee_shift'] ?? '-'));
    $this->line('To employee shift baru: ' . (string) ($result['to_employee_shift'] ?? '-'));
    return 0;
})->purpose('Replace roster personel security pada tanggal tertentu');
